const quizSets={
  'Market entry fundamentals':{tag:'PRODUCT STRATEGY',questions:[['Which question should a product team answer first when evaluating a new market?',['How can we build the most features?','What painful problem is worth solving for a specific group?','Which competitor has the biggest ad budget?','How quickly can we launch globally?'],1],['A beachhead market is best described as...',['The largest market available','A market with no competition','A focused first segment that creates momentum','A market that only buys seasonal products'],2],['What does a strong value proposition make clear?',['The team’s internal process','Why this solution is meaningfully better for a target customer','Every possible future feature','The exact size of the company'],1]]},
  'Biases & decision making':{tag:'BEHAVIORAL ECONOMICS',questions:[['Which bias makes people favor information that confirms what they already believe?',['Confirmation bias','Recency bias','Survivorship bias','The decoy effect'],0],['A default option is powerful because it...',['Always costs less','Reduces the effort required to decide','Removes all available choices','Makes a product more colorful'],1],['The sunk cost fallacy can cause someone to...',['Try something new quickly','Ignore prior investments','Continue a poor choice because they have already invested in it','Choose the cheapest option'],2]]},
  'Tokens, type & rhythm':{tag:'DESIGN SYSTEMS',questions:[['What is a design token?',['A reusable decision like a color, size, or spacing value','A final product mockup','A user research interview','A type of animation'],0],['A spacing scale helps a design system...',['Create random layouts','Keep distance relationships consistent','Remove the need for typography','Only support mobile screens'],1],['Which is a good reason to use a type hierarchy?',['To make every heading identical','To help people scan and understand content structure','To hide important information','To increase the number of colors'],1]]}
};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s); let toastTimer;
function toast(message){$('#toast span').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function view(name){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===name));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#crumb').textContent=name==='today'?'Today':name==='practice'?'Practice exams':name[0].toUpperCase()+name.slice(1);window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(n=>n.onclick=()=>view(n.dataset.view));
$$('.class').forEach(c=>c.onclick=()=>{ $$('.class').forEach(x=>x.classList.remove('active-class'));c.classList.add('active-class');toast('Class selected. Keep the momentum going!')});
const exams=[['Market entry fundamentals','PRODUCT STRATEGY','Practice the frameworks behind finding a wedge, sizing an opportunity, and shipping a smarter first move.','20 questions','18 min','featured'],['Biases & decision making','BEHAVIORAL ECONOMICS','Spot the invisible shortcuts that shape choices, pricing, and everyday behavior.','15 questions','12 min','orange'],['Tokens, type & rhythm','DESIGN SYSTEMS','Put the building blocks of a flexible visual language into practice.','18 questions','15 min','blue']];
$('#exam-grid').innerHTML=exams.map((e,i)=>`<article class="exam ${e[5]}"><span class="tag ${e[5]}">${e[1]}</span><h2>${e[0]}</h2><p>${e[2]}</p><div class="exam-meta">◷ ${e[4]}　▣ ${e[3]}　 ● Medium</div><footer><div><small><b>${i?0:7}</b> / ${e[3].split(' ')[0]} complete</small><div class="progress"><i style="width:${i?0:35}%"></i></div></div><button class="primary start" data-exam="${e[0]}">Start exam →</button></footer></article>`).join('');
$$('.start').forEach(b=>b.onclick=()=>openQuiz(b.dataset.exam));
$('#quick-start').onclick=$('#continue').onclick=()=>openQuiz('Market entry fundamentals');$('#random').onclick=()=>openQuiz('Biases & decision making');$('#final-push').onclick=()=>openQuiz('Tokens, type & rhythm');$('#progress').onclick=()=>toast('Your strongest topic is customer discovery. Nice work!');$('#earn').onclick=()=>{view('practice');toast('One focused exam can move you up. Let’s do it!')};$('#create-room').onclick=()=>toast('Room created! Share the invite with your study crew.');$('#join-live').onclick=()=>toast('You joined Friday night sprint. Get ready!');$$('.join').forEach(b=>b.onclick=()=>toast('You’re in! The game starts when the room fills.'));
$$('.filters button').forEach(b=>b.onclick=()=>{if(b.textContent.includes('Sort'))return;$$('.filters button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');toast(`${b.textContent} view selected.`)});
let quiz,question=0,score=0,selected=null;function openQuiz(name){quiz=quizSets[name];question=0;score=0;$('#quiz-title').textContent=name;$('#quiz-class').textContent=quiz.tag;$('#modal').classList.add('open');render()}
function render(){const q=quiz.questions[question];selected=null;$('#counter').textContent=`Question ${question+1} of ${quiz.questions.length}`;$('#quiz-bar').style.width=`${(question+1)/quiz.questions.length*100}%`;$('#prompt').textContent=q[0];$('#feedback').textContent='Choose the best answer.';$('#next').disabled=true;$('#next').textContent=question===quiz.questions.length-1?'Finish sprint →':'Check answer →';$('#answers').innerHTML=q[1].map((a,i)=>`<button class="answer" data-i="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>choose(+b.dataset.i,b))}
function choose(i,b){if(selected!==null)return;selected=i;const correct=quiz.questions[question][2];$$('.answer').forEach(x=>x.disabled=true);b.classList.add(i===correct?'correct':'incorrect');if(i!==correct)$$('.answer')[correct].classList.add('correct');if(i===correct){score++;$('#feedback').textContent='That’s it. Your instincts are getting sharper.'}else $('#feedback').textContent='Good attempt. The explanation is part of the win.';$('#next').disabled=false}
$('#next').onclick=()=>{if(question<quiz.questions.length-1){question++;render()}else{$('#modal').classList.remove('open');const earned=score*20+20;$('#points').textContent=(1284+earned).toLocaleString();toast(`Sprint complete: ${score}/${quiz.questions.length}. +${earned} points!`)}};$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};
